version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
  web:
    build: .
    command: sh -c "sleep 30 && python manage.py runserver 0.0.0.0:8000"
    container_name: service
    volumes:
      - .:/service
    ports:
      - "8000:8000"
    depends_on:
      - db